config/routes.rb
Rails.application.routes.draw do
  get '/cart', to: 'orders#cart', as: :cart
  get '/cart/add-item/:variant_id', to: 'orders#add_item_cart', as: :add_item_cart
  post '/cart/add-item', to: 'orders#add_item_cart', as: :add_item_cart_post
  get '/cart/remove-item/:variant_id', to: 'orders#remove_item_cart', as: :remove_item_cart
  patch '/cart', to: 'orders#update_cart', as: :update_cart
  get '/checkout', to: 'orders#checkout', as: :checkout
  patch '/checkout/:state', :to => 'orders#update_checkout', :as => :update_checkout
  get '/checkout/:state', :to => 'orders#checkout', :as => :checkout_state

  root to: "pages#home"
  mount Spree::Core::Engine, at: '/'

  resources :products
  devise_for :users, controllers: {registrations: 'registrations', sessions: 'sessions'}

  get '/contact' => "pages#contact"
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :check_authorization, except: [:checkout, :update_checkout]
  rescue_from ActiveRecord::RecordNotFound, :with => :render_404
  helper 'spree/products', 'spree/orders'

  respond_to :html

  before_filter :assign_order_with_lock, only: [ :remove_item_cart, :update_cart ]
  
  before_action :load_order_with_lock, only: [:checkout, :update_checkout]
  before_filter :ensure_valid_state_lock_version, only: [:update_checkout]
  before_filter :set_state_if_present, only: [:checkout, :update_checkout]

  before_action :ensure_order_not_completed, only: [:checkout, :update_checkout]
  before_action :ensure_checkout_allowed, only: [:checkout, :update_checkout]
  before_action :ensure_sufficient_stock_lines, only: [:checkout, :update_checkout]
  before_action :ensure_valid_state, only: [:checkout, :update_checkout]

  before_action :associate_user, only: [:checkout, :update_checkout]
  before_action :check_authorization_checkout, only: [:checkout, :update_checkout]
  #before_action :apply_coupon_code, only: [:checkout, :update_checkout]

  before_action :setup_for_current_state, only: [:checkout, :update_checkout]

  helper 'spree/orders'

  def cart
    @order = current_order || Spree::Order.new
    associate_user
  end

  def add_item_cart
    quantity = params[:quantity] || 1
    populator = Spree::OrderPopulator.new(current_order(create_order_if_necessary: true), current_currency)
    if populator.populate(params[:variant_id], quantity, params[:options])
      redirect_to cart_path
    else
      flash[:error] = populator.errors.full_messages.join(" ")
      redirect_back_or_default(root_path)
    end
  end

  def remove_item_cart
    @line_item = @order.line_items.find(params[:variant_id])
    @order.contents.remove(@line_item.variant, @line_item.quantity, {})

    respond_to do |format|
      format.html { redirect_to cart_path }
      format.js
    end
  end

  def update_cart
    if @order.contents.update_cart(order_params)
      respond_with(@order) do |format|
        format.html do
          if params.has_key?(:checkout)
            @order.next if @order.cart?
            redirect_to checkout_state_path(@order.checkout_steps.first)
          else
            redirect_to cart_path
          end
        end
      end
    else
      respond_with(@order)
    end
  end

  def checkout
    before_address
  end

  def update_checkout
    if @order.update_from_params(params, permitted_checkout_attributes, request.headers.env)
      @order.temporary_address = !params[:save_user_address]
      unless @order.next
        flash[:error] = @order.errors.full_messages.join("\n")
        redirect_to checkout_state_path(@order.state) and return
      end

      if @order.completed?
        @current_order = nil
        flash.notice = Spree.t(:order_processed_successfully)
        flash['order_completed'] = true
        redirect_to completion_route
      else
        redirect_to checkout_state_path(@order.state)
      end
    else
      render :checkout
    end
  end

  private
  def before_address
    # if the user has a default address, a callback takes care of setting
    # that; but if he doesn't, we need to build an empty one here
    @order.bill_address ||= Spree::Address.build_default
    @order.ship_address ||= Spree::Address.build_default if @order.checkout_steps.include?('delivery')
  end

  def check_authorization
    cookies.permanent.signed[:guest_token] = params[:token] if params[:token]
    order = Spree::Order.find_by_number(params[:id]) || current_order

    if order
      authorize! :edit, order, cookies.signed[:guest_token]
    else
      authorize! :create, Spree::Order
    end
  end

  def order_params
    if params[:order]
      params[:order]#.permit(*Spree::permitted_order_attributes)
    else
      {}
    end
  end

  def assign_order_with_lock
    @order = current_order(lock: true)
    unless @order
      flash[:error] = Spree.t(:order_not_found)
      redirect_to root_path and return
    end
  end

  # Checkout

  def ensure_valid_state
    unless skip_state_validation?
      if (params[:state] && !@order.has_checkout_step?(params[:state])) ||
          (!params[:state] && !@order.has_checkout_step?(@order.state))
        @order.state = 'cart'
        redirect_to checkout_state_path(@order.checkout_steps.first)
      end
    end

    # Fix for #4117
    # If confirmation of payment fails, redirect back to payment screen
    if params[:state] == "confirm" && @order.payment_required? && @order.payments.valid.empty?
      flash.keep
      redirect_to checkout_state_path("payment")
    end
  end

  # Should be overriden if you have areas of your checkout that don't match
  # up to a step within checkout_steps, such as a registration step
  def skip_state_validation?
    false
  end

  def load_order_with_lock
    @order = current_order(lock: true)
    redirect_to cart_path and return unless @order
  end

  def ensure_valid_state_lock_version
    if params[:order] && params[:order][:state_lock_version]
      @order.with_lock do
        unless @order.state_lock_version == params[:order].delete(:state_lock_version).to_i
          flash[:error] = Spree.t(:order_already_updated)
          redirect_to checkout_state_path(@order.state) and return
        end
        @order.increment!(:state_lock_version)
      end
    end
  end

  def set_state_if_present
    if params[:state]
      redirect_to checkout_state_path(@order.state) if @order.can_go_to_state?(params[:state]) && !skip_state_validation?
      @order.state = params[:state]
    end
  end

  def ensure_checkout_allowed
    unless @order.checkout_allowed?
      redirect_to cart_path
    end
  end

  def ensure_order_not_completed
    redirect_to spree.cart_path if @order.completed?
  end

  def ensure_sufficient_stock_lines
    if @order.insufficient_stock_lines.present?
      flash[:error] = Spree.t(:inventory_error_flash_for_insufficient_quantity)
      redirect_to spree.cart_path
    end
  end

  # Provides a route to redirect after order completion
  def completion_route
    spree.order_path(@order)
  end

  def setup_for_current_state
    method_name = :"before_#{@order.state}"
    send(method_name) if respond_to?(method_name, true)
  end

  def before_address
    # if the user has a default address, a callback takes care of setting
    # that; but if he doesn't, we need to build an empty one here
    @order.bill_address ||= Spree::Address.build_default
    @order.ship_address ||= Spree::Address.build_default if @order.checkout_steps.include?('delivery')
  end

  def before_delivery
    return if params[:order].present?

    packages = @order.shipments.map { |s| s.to_package }
    @differentiator = Spree::Stock::Differentiator.new(@order, packages)
  end

  def before_payment
    if @order.checkout_steps.include? "delivery"
      packages = @order.shipments.map { |s| s.to_package }
      @differentiator = Spree::Stock::Differentiator.new(@order, packages)
      @differentiator.missing.each do |variant, quantity|
        @order.contents.remove(variant, quantity)
      end
    end

    if try_spree_current_user && try_spree_current_user.respond_to?(:payment_sources)
      @payment_sources = try_spree_current_user.payment_sources
    end
  end

  def rescue_from_spree_gateway_error(exception)
    flash.now[:error] = Spree.t(:spree_gateway_error_flash_for_checkout)
    @order.errors.add(:base, exception.message)
    render :edit
  end

  def check_authorization_checkout
    authorize!(:edit, current_order, cookies.signed[:guest_token])
  end
end

app/views/orders/_address.html.erb
<div class="row">
  <div class="col-md-6" data-hook="billing_fieldset_wrapper">
    <fieldset id="billing" data-hook>
      <%= form.fields_for :bill_address do |bill_form| %>
        <legend align="center"><%= Spree.t(:billing_address) %></legend>
        <%= render :partial => 'address_form', :locals => { :form => bill_form, :address_type => 'billing', :address => @order.bill_address } %>
      <% end %>
    </fieldset>
  </div>

  <div class="col-md-6" data-hook="shipping_fieldset_wrapper">
    <fieldset id="shipping" data-hook>
      <%= form.fields_for :ship_address do |ship_form| %>
        <legend align="center"><%= Spree.t(:shipping_address) %></legend>
        <p class="field checkbox" data-hook="use_billing">
          <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address? %>
          <%= label_tag :order_use_billing, Spree.t(:use_billing_address), :id => 'use_billing' %>
        </p>
        <%= render :partial => 'address_form', :locals => { :form => ship_form, :address_type => 'shipping', :address => @order.ship_address } %>
      <% end %>
    </fieldset>
  </div>
</div>

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), :class => 'btn btn-primary' %>
  <% if try_spree_current_user %>
    <%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
    <%= label_tag :save_user_address, Spree.t(:save_my_address) %>
  <% end %>
</div>

app/views/orders/_address_form.html.erb
<% address_id = address_type.chars.first %>
<div class="inner" data-hook=<%="#{address_type}_inner" %>>
  <p class="field" id=<%="#{address_id}firstname" %>>
    <%= form.label :firstname, Spree.t(:first_name) %><span class="required">*</span><br />
    <%= form.text_field :firstname, :class => 'required' %>
  </p>
  <p class="field" id=<%="#{address_id}lastname" %>>
    <%= form.label :lastname, Spree.t(:last_name) %><span class="required">*</span><br />
    <%= form.text_field :lastname, :class => 'required' %>
  </p>
  <% if Spree::Config[:company] %>
    <p class="field" id=<%="#{address_id}company" %>>
      <%= form.label :company, Spree.t(:company) %><br />
      <%= form.text_field :company %>
    </p>
  <% end %>
  <p class="field" id=<%="#{address_id}address1" %>>
    <%= form.label :address1, Spree.t(:street_address) %><span class="required">*</span><br />
    <%= form.text_field :address1, :class => 'required' %>
  </p>
  <p class="field" id=<%="#{address_id}address2" %>>
    <%= form.label :address2, Spree.t(:street_address_2) %><br />
    <%= form.text_field :address2 %>
  </p>
  <p class="field" id=<%="#{address_id}city" %>>
    <%= form.label :city, Spree.t(:city) %><span class="required">*</span><br />
    <%= form.text_field :city, :class => 'required' %>
  </p>
  <p class="field" id=<%="#{address_id}country" %>>
    <%= form.label :country_id, Spree.t(:country) %><span class="required">*</span><br />
    <span id=<%="#{address_id}country-selection" %>>
      <%= form.collection_select :country_id, available_countries, :id, :name, {}, {:class => 'required'} %>
    </span>
  </p>

  <% if Spree::Config[:address_requires_state] %>
    <p class="field" id=<%="#{address_id}state" %>>
      <% have_states = !address.country.states.empty? %>
      <%= form.label :state, Spree.t(:state) %><span class='required' id=<%="#{address_id}state-required"%>>*</span><br/>

      <% state_elements = [
         form.collection_select(:state_id, address.country.states,
                            :id, :name,
                            {:include_blank => true},
                            {:class => have_states ? 'required' : 'hidden',
                            :disabled => !have_states}) +
         form.text_field(:state_name,
                            :class => !have_states ? 'required' : 'hidden',
                            :disabled => have_states)
         ].join.gsub('"', "'").gsub("\n", "")
      %>
      <%= javascript_tag do -%>
        $('#<%="#{address_id}state" %>').append("<%== state_elements %>");
      <% end %>
    </p>
      <noscript>
        <%= form.text_field :state_name, :class => 'required' %>
      </noscript>
  <% end %>

  <p class="field" id=<%="#{address_id}zipcode" %>>
    <%= form.label :zipcode, Spree.t(:zip) %><% if address.require_zipcode? %><span class="required">*</span><br /><% end %>
    <%= form.text_field :zipcode, :class => "#{'required' if address.require_zipcode?}" %>
  </p>
  <p class="field" id=<%="#{address_id}phone" %>>
    <%= form.label :phone, Spree.t(:phone) %><% if address.require_phone? %><span class="required">*</span><br /><% end %>
    <%= form.phone_field :phone, :class => "#{'required' if address.require_phone?}" %>
  </p>
  <% if Spree::Config[:alternative_shipping_phone] %>
    <p class="field" id=<%="#{address_id}altphone" %>>
      <%= form.label :alternative_phone, Spree.t(:alternative_phone) %><br />
      <%= form.phone_field :alternative_phone %>
    </p>
  <% end %>
</div>

app/views/orders/_delivery.html.erb
<fieldset id='shipping_method' data-hook>
  <legend align="center"><%= Spree.t(:delivery) %></legend>
  <div class="inner" data-hook="shipping_method_inner">
    <div id="methods">
      <%= form.fields_for :shipments do |ship_form| %>

        <div class="shipment">
          <h3 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:package_from) %>
            <strong class="stock-location-name" data-hook="stock-location-name"><%= ship_form.object.stock_location.name %></strong>
          </h3>

          <table class="stock-contents" data-hook="stock-contents">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% ship_form.object.manifest.each do |item| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(item.variant) %></td>
                  <td class="item-name"><%= item.variant.name %></td>
                  <td class="item-qty"><%= item.quantity %></td>
                  <td class="item-price"><%= display_price(item.variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>

          <h5 class="stock-shipping-method-title"><%= Spree.t(:shipping_method) %></h5>
          <ul class="field radios shipping-methods">
            <% ship_form.object.shipping_rates.each do |rate| %>
              <li class="shipping-method">
                <label>
                  <%= ship_form.radio_button :selected_shipping_rate_id, rate.id %>
                  <span class="rate-name"><%= rate.name %></span>
                  <span class="rate-cost"><%= rate.display_cost %></span>
                </label>
              </li>
            <% end %>
          </ul>
        </div>

      <% end %>

      <% if @differentiator.try(:missing?) %>
        <div class="shipment unshippable">
          <h3 class="stock-location" data-hook="stock-location">
            <%= Spree.t(:unshippable_items) %>
          </h3>
          <table class="stock-contents" data-hook="stock-missing">
            <colgroup>
              <col style="width: 10%;" />
              <col style="width: 60%;" />
              <col style="width: 10%;" />
              <col style="width: 20%;" />
            </colgroup>
            <thead>
              <th></th>
              <th align='left'><%= Spree.t(:item) %></th>
              <th><%= Spree.t(:qty) %></th>
              <th><%= Spree.t(:price) %></th>
            </thead>
            <tbody>
              <% @differentiator.missing.each do |variant, quantity| %>
                <tr class="stock-item">
                  <td class="item-image"><%= mini_image(variant) %></td>
                  <td class="item-name"><%= variant.name %></td>
                  <td class="item-qty"><%= quantity %></td>
                  <td class="item-price"><%= display_price(variant) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      <% end %>

    </div>
    <% if Spree::Config[:shipping_instructions] %>
      <p id="minstrs" data-hook>
        <%= form.label :special_instructions, Spree.t(:shipping_instructions) %><br />
        <%= form.text_area :special_instructions, :cols => 40, :rows => 7 %>
      </p>
    <% end %>
  </div>
</fieldset>

<br />

<div class="form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), :class => 'continue button primary' %>
</div>

app/views/orders/_form.html.erb
<% address_id = address_type.chars.first %>
<div class="inner" data-hook=<%="#{address_type}_inner" %>>
  <p class="field" id=<%="#{address_id}firstname" %>>
    <%= form.label :firstname, Spree.t(:first_name) %><span class="required">*</span><br />
    <%= form.text_field :firstname, :class => 'required' %>
  </p>
  <p class="field" id=<%="#{address_id}lastname" %>>
    <%= form.label :lastname, Spree.t(:last_name) %><span class="required">*</span><br />
    <%= form.text_field :lastname, :class => 'required' %>
  </p>
  <% if Spree::Config[:company] %>
    <p class="field" id=<%="#{address_id}company" %>>
      <%= form.label :company, Spree.t(:company) %><br />
      <%= form.text_field :company %>
    </p>
  <% end %>
  <p class="field" id=<%="#{address_id}address1" %>>
    <%= form.label :address1, Spree.t(:street_address) %><span class="required">*</span><br />
    <%= form.text_field :address1, :class => 'required' %>
  </p>
  <p class="field" id=<%="#{address_id}address2" %>>
    <%= form.label :address2, Spree.t(:street_address_2) %><br />
    <%= form.text_field :address2 %>
  </p>
  <p class="field" id=<%="#{address_id}city" %>>
    <%= form.label :city, Spree.t(:city) %><span class="required">*</span><br />
    <%= form.text_field :city, :class => 'required' %>
  </p>
  <p class="field" id=<%="#{address_id}country" %>>
    <%= form.label :country_id, Spree.t(:country) %><span class="required">*</span><br />
    <span id=<%="#{address_id}country-selection" %>>
      <%= form.collection_select :country_id, available_countries, :id, :name, {}, {:class => 'required'} %>
    </span>
  </p>

  <% if Spree::Config[:address_requires_state] %>
    <p class="field" id=<%="#{address_id}state" %>>
      <% have_states = !address.country.states.empty? %>
      <%= form.label :state, Spree.t(:state) %><span class='required' id=<%="#{address_id}state-required"%>>*</span><br/>

      <% state_elements = [
         form.collection_select(:state_id, address.country.states,
                            :id, :name,
                            {:include_blank => true},
                            {:class => have_states ? 'required' : 'hidden',
                            :disabled => !have_states}) +
         form.text_field(:state_name,
                            :class => !have_states ? 'required' : 'hidden',
                            :disabled => have_states)
         ].join.gsub('"', "'").gsub("\n", "")
      %>
      <%= javascript_tag do -%>
        $('#<%="#{address_id}state" %>').append("<%== state_elements %>");
      <% end %>
    </p>
      <noscript>
        <%= form.text_field :state_name, :class => 'required' %>
      </noscript>
  <% end %>

  <p class="field" id=<%="#{address_id}zipcode" %>>
    <%= form.label :zipcode, Spree.t(:zip) %><% if address.require_zipcode? %><span class="required">*</span><br /><% end %>
    <%= form.text_field :zipcode, :class => "#{'required' if address.require_zipcode?}" %>
  </p>
  <p class="field" id=<%="#{address_id}phone" %>>
    <%= form.label :phone, Spree.t(:phone) %><% if address.require_phone? %><span class="required">*</span><br /><% end %>
    <%= form.phone_field :phone, :class => "#{'required' if address.require_phone?}" %>
  </p>
  <% if Spree::Config[:alternative_shipping_phone] %>
    <p class="field" id=<%="#{address_id}altphone" %>>
      <%= form.label :alternative_phone, Spree.t(:alternative_phone) %><br />
      <%= form.phone_field :alternative_phone %>
    </p>
  <% end %>
</div>

app/views/orders/cart.html.erb
<%= form_for @order, url: update_cart_path, html: {id: 'update-cart'} do |order_form| %>
  <section id="cart_items">
    <div class="container">
      <div class="breadcrumbs">
        <ol class="breadcrumb">
          <li><a href="#">Home</a></li>
          <li class="active">Shopping Cart</li>
        </ol>
      </div>
      <div class="table-responsive cart_info">
        <table class="table table-condensed">
          <thead>
            <tr class="cart_menu">
              <td class="image">
                <%= Spree.t(:item) %>
              </td>
              <td class="description"></td>
              <td class="price">
                <%= Spree.t(:price) %>
              </td>
              <td class="quantity">
                <%= Spree.t(:qty) %>
              </td>
              <td class="total">
                <%= Spree.t(:total) %>
              </td>
              <td></td>
            </tr>
          </thead>
          <tbody>
            <% if @order.line_items.empty? %>
              <tr class="line-item">
                <td colspan="5">
                  <h3 class="text-center">Your Shopping Cart is Empty</h3>
                </td>
              </tr>
              <tr class="line-item">
                <td colspan="5">
                  <span class="col-sm-4"></span>
                  <span class="col-sm-4"><%= image_tag('cart/empty.gif', class: 'img-responsive') %></span>
                  <span class="col-sm-4"></span>
                </td>
              </tr>
            <% end %>
            <% @order.line_items.each do |line_item| %>
              <% variant = line_item.variant -%>
              <%= order_form.fields_for :line_items, line_item do |item_form| %>
                <tr class="line-item" id="line-item-<%= line_item.id %>">
                  <td class="cart_product">
                    <% if variant.images.length == 0 %>
                      <%= link_to small_image(variant.product), variant.product %>
                    <% else %>
                      <%= link_to image_tag(variant.images.first.attachment.url(:small)), variant.product %>
                    <% end %>
                  </td>

                  <td class="cart_description">
                    <h4><%= link_to line_item.name, product_path(variant.product) %></h4>
                    <%= variant.options_text %>
                    <% if line_item.insufficient_stock? %>
                      <span class="out-of-stock">
                        <%= Spree.t(:out_of_stock) %>&nbsp;&nbsp;<br />
                      </span>
                    <% end %>
                    <span class="line-item-description" data-hook="line_item_description">
                      <%= line_item_description_text(line_item.description) %>
                    </span>
                  </td>

                  <td class="cart_price">
                    <p><%= line_item.single_money.to_html %></p>
                  </td>

                  <td class="cart_quantity">
                    <div class="cart_quantity_button">
                      <a class="cart_quantity_up"><i class="fa fa-plus"></i></a>
                      <%= item_form.number_field :quantity, min: 1, class: "cart_quantity_input", size: 2 %>
                      <a class="cart_quantity_down"><i class="fa fa-minus"></i></a>
                    </div>
                  </td>

                  <td class="cart_total">
                    <p class="cart_total_price"><%= line_item.display_amount.to_html unless line_item.quantity.nil? %></p>
                  </td>

                  <td class="cart_delete">
                    <%= link_to remove_item_cart_path(line_item.id), class: 'cart_quantity_delete delete', data: {confirm: "Are you sure?"}, remote: true do %>
                      <i class="fa fa-times"></i>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </section>

  <section id="do_action">
    <div class="container">
      <div class="heading">
        <h3>What would you like to do next?</h3>
        <p>Choose if you have a discount code or reward points you want to use or would like to estimate your delivery cost.</p>
      </div>
      <div class="row">
        <div class="col-sm-6">
          <div class="chose_area">
            <ul class="user_option">
              <li>
                <input type="checkbox">
                <label>Use Coupon Code</label>
              </li>
              <li>
                <input type="checkbox">
                <label>Use Gift Voucher</label>
              </li>
              <li>
                <input type="checkbox">
                <label>Estimate Shipping & Taxes</label>
              </li>
            </ul>
            <ul class="user_info">
              <li class="single_field">
                <label>Country:</label>
                <select>
                  <option>United States</option>
                  <option>Bangladesh</option>
                  <option>UK</option>
                  <option>India</option>
                  <option>Pakistan</option>
                  <option>Ucrane</option>
                  <option>Canada</option>
                  <option>Dubai</option>
                </select>
              </li>
              <li class="single_field">
                <label>Region / State:</label>
                <select>
                  <option>Select</option>
                  <option>Dhaka</option>
                  <option>London</option>
                  <option>Dillih</option>
                  <option>Lahore</option>
                  <option>Alaska</option>
                  <option>Canada</option>
                  <option>Dubai</option>
                </select>
              </li>
              <li class="single_field zip-field">
                <label>Zip Code:</label>
                <input type="text">
              </li>
              <li>
                <%= order_form.text_field :coupon_code, size: 10, placeholder: Spree.t(:coupon_code) %>
              </li>
            </ul>
            <a class="btn btn-default update" href="">Get Quotes</a>
            <a class="btn btn-default check_out" href="">Continue</a>
          </div>
        </div>
        <div class="col-sm-6">
          <div class="total_area">
            <ul>
              <li>Cart Sub Total <span><%= @order.display_item_total.to_html %></span></li>
              <li>Eco Tax <span>$2</span></li>
              <li>Shipping Cost <span>Free</span></li>
              <li>Total <span><%= @order.display_total.to_html %></span></li>
            </ul>
            <%= button_tag class: 'btn btn-default update', id: 'update-button' do %>
              <%= Spree.t(:update) %>
            <% end %>
            <%= button_tag class: 'btn btn-default check_out', id: 'checkout-link', name: 'checkout' do %>
              <i class="fa fa-crosshairs"></i> <%= Spree.t(:checkout) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/orders/checkout.html.erb
<%= form_for @order, :url => update_checkout_path(@order.state), :html => { :id => "checkout_form_#{@order.state}" } do |form| %>
  <section id="cart_items">
    <div class="container">
      <div class="breadcrumbs">
        <ol class="breadcrumb">
          <li><a href="#">Home</a></li>
          <li class="active">Check out</li>
        </ol>
      </div>

      <div class="step-one">
        <h2 class="heading">State <%= @order.state %></h2>
      </div>

      <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %></h2>

          <ul>
          <% @order.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <%= render @order.state, :form => form %>
    </div>
  </section>
<% end %>

app/views/orders/remove_item_cart.js.erb
$('#line-item-<%= @line_item.id %>').remove();